### ISSUE TITLE
contains()/containsIgnoreCase() does not work with reactive driver

### ISSUE THREAD

**Issue by torben-w** [jklingsporn/vertx-jooq#93] opened 2019-01-22 09:37 UTC
Database: postgreSQL 9.6
vertx-jooq: classic-reactive 4.0.0
jOOQ: 3.11.5
vertx: 3.5.4

I just updated my project from _vertx-jooq-classic-async (version 4.0.0-BETA)_ to _vertx-jooq-classic-reactive (4.0.0)_.

I have _CustomDaos_ which inherit from the generated Daos. In those I've declared some custom sql statements like:

    public Future<List<Row>> findManyBySearchString(String search) {
        return queryExecutor().findManyRow(dslContext -> {

            final SelectHavingStep<Record> test = dslContext
                    .select(TABLE_ONE.UUID, TABLE_ONE.SOME_STRING, TABLE_ONE.SOME_OTHER_STRING)
                    .from(TABLE_ONE)
                    .where(TABLE_ONE.SOME_STRING.containsIgnoreCase(search))
                    .or(TABLE_ONE.SOME_OTHER_STRING.containsIgnoreCase(search));

            System.out.println(test.toString());

            return test;
        }
    }

If I call this method with the search string "test", then this sql statement will be generated:

    select 
      "testschema"."table_one"."uuid", "testschema"."table_one"."some_string", "testschema"."table_one"."some_other_string"
    from "testschema"."table_one"
    where (
      "testschema"."table_one"."some_string" ilike ('%' || 'test' || '%') escape '!'
       or "testschema"."table_one"."some_other_string" ilike ('%' || 'test' || '%') escape '!'
    )

And the following exception will be thrown:

`io.vertx.core.impl.NoStackTraceThrowable: Values [%, test, %, !] cannot be coerced to [String]`

The same applies for like("%" + search + "%", '\\\\') / likeIgnoreCase("%" + search + "%", '\\\\'). So the binding does not work when something has to be escaped when using the reactive driver (version 4.0.0).

With the async driver and version 4.0.0-BETA the same code (only difference due to the implementation of vertx-jooq: JsonObject instead of Row and therefore findManyJson() instead of findManyRow()) worked fine.

**Comment by torben-w** [comment] 2019-01-22 14:43
I think I found another case where the same error occurs:

    int someid = 1;

    final Future<List<Row>> someEntities = queryExecutor().findManyRow(dslContext -> dslContext
                    .selectFrom(SOME_TABLE)
                    .where(SOME_TABLE.ISDELETED.isFalse())
                    .and(SOME_TABLE.SOME_ID.eq(someid)));

This throws the following exception:
`io.vertx.core.impl.NoStackTraceThrowable: Values [false, 3] cannot be coerced to [Number]`

**Comment by jklingsporn** [comment] 2019-01-29 10:10
I managed to reproduce the problem with the reactive driver (JDBC and async worked fine).

**Comment by jklingsporn** [comment] 2019-01-29 10:36
Here is what happens under the hood for the reactive driver:

`dao.queryExecutor().findManyRow(dslContext -> dslContext.selectFrom(Tables.SOMETHING).where(Tables.SOMETHING.SOMESTRING.containsIgnoreCase("my_string"))`

 is translated to the following SQL 
`select 
  "vertx"."something"."someId", 
  "vertx"."something"."someString", 
  "vertx"."something"."someHugeNumber", 
  "vertx"."something"."someSmallNumber", 
  "vertx"."something"."someRegularNumber", 
  "vertx"."something"."someDouble", 
  "vertx"."something"."someEnum", 
  "vertx"."something"."someJsonObject", 
  "vertx"."something"."someJsonArray", 
  "vertx"."something"."someTimestamp"
from "vertx"."something"
where "vertx"."something"."someString" ilike ('%' || 'my!_string' || '%') escape '!'`

Because `vertx-jooq` uses prepared statements for query execution, I need to extract the parameters from the query by calling `query.getParams()` on a jOOQ-Query and add the result to a PGClient Tuple. The function returns 4 elements that are added as strings: `'%', 'my_!string', '%' '!'` On the other the actual query used in the statement looks like this: `select "vertx"."something"."someId", "vertx"."something"."someString", "vertx"."something"."someHugeNumber", "vertx"."something"."someSmallNumber", "vertx"."something"."someRegularNumber", "vertx"."something"."someDouble", "vertx"."something"."someEnum", "vertx"."something"."someJsonObject", "vertx"."something"."someJsonArray", "vertx"."something"."someTimestamp" from "vertx"."something" where "vertx"."something"."someString" ilike ('%' || $1 || '%') escape '!'`

so it only expects one argument instead of four. Until I've found a fix for this you may write a workaround by writing the query on your own and not use the jOOQ convenience method `containsIgnoreCase`.

**Comment by jklingsporn** [comment] 2019-01-29 10:45
Fixed by only returning jOOQ-Params that are not inlined in `getBindValues` like this:
```
protected Tuple getBindValues(Query query) {
        ArrayTuple bindValues = new ArrayTuple(query.getParams().size());
        for (Param<?> param : query.getParams().values()) {
            if(!param.isInline()){
                Object value = convertToDatabaseType(param);
                bindValues.add(value);
            }
        }
        return bindValues;
    }

**Closed** 2019-02-08 10:57 UTC
Labels: bug
